name: compile and deploy to gh-pages branch

on:
    push:
        branches: main

jobs:
    compile-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v4

            - name: initialize nodejs
              uses: actions/setup-node@v4
            - name: init npm packages
              run: npm install

            - name: compile typescript to javascript using tsc
              run: npx tsc

            - name: insert using txtinsert
              run: |
                wget https://github.com/thepigeongenerator/text_inserter/releases/latest/download/txtinsert -O /tmp/txtinsert
                chmod +x /tmp/txtinsert
                git ls-files *.html | xargs /tmp/txtinsert
                rm /tmp/txtinsert

            - name: add website gitignore
              run: cat .website_ignore >> .gitignore

            - name: deploy to gh-pages branch
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_branch: gh-pages
                publish_dir: "."
